import React, { useState } from 'react';
import { X, FileText, Download, Copy, Check, ShieldCheck, Printer } from 'lucide-react';
import { SatQueryResponse } from '../types';

interface ReportModalProps {
  response: SatQueryResponse | null;
  isOpen: boolean;
  onClose: () => void;
}

export const ReportModal: React.FC<ReportModalProps> = ({
  response,
  isOpen,
  onClose
}) => {
  const [copied, setCopied] = useState(false);
  const [format, setFormat] = useState<'markdown' | 'json'>('markdown');

  if (!isOpen || !response) return null;

  const markdownContent = `# SatQuery AI — Remote Sensing Analysis Forensic Report
**Query ID:** \`${response.queryId}\`
**Date/Time:** ${response.executionTrace.timestamp}
**Target Task:** ${response.taskType.toUpperCase()}
**Confidence Score:** ${(response.confidence * 100).toFixed(1)}%

---

## 1. Geospatial Query
> "${response.query}"

---

## 2. Model Assessment & Findings
${response.answer}

---

## 3. Remote Sensing Evidence
- **Task Category:** ${response.evidence.taskType}
- **Bounding Boxes Detected:** ${response.evidence.boundingBoxes ? response.evidence.boundingBoxes.length : 0}
${response.evidence.spectralStats ? `- **Mean NDVI:** ${response.evidence.spectralStats.meanNdvi} | **Vegetation Status:** ${response.evidence.spectralStats.vegetationHealth}` : ''}
${response.evidence.changeAnalysis ? `- **Change Event:** ${response.evidence.changeAnalysis.changeType} | **Severity:** ${response.evidence.changeAnalysis.severity} | **Affected Area:** ${response.evidence.changeAnalysis.affectedAreaPercentage}%` : ''}

---

## 4. Execution Trace & Audit
- **Primary VLM:** ${response.executionTrace.primaryModel}
- **Domain Adapter:** ${response.executionTrace.adaptedModel}
- **Total Latency:** ${response.executionTrace.totalDurationMs} ms
- **Steps:** ${response.executionTrace.steps.length} sequential execution stages

*Audited and generated by SatQuery AI (BigEarthNet-19 Adapted Remote Sensing Assistant).*
`;

  const downloadFile = (content: string, filename: string, type: string) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleDownload = () => {
    if (format === 'markdown') {
      downloadFile(markdownContent, `SatQuery_Report_${response.queryId}.md`, 'text/markdown');
    } else {
      downloadFile(JSON.stringify(response, null, 2), `SatQuery_Report_${response.queryId}.json`, 'application/json');
    }
  };

  const handleCopy = () => {
    const text = format === 'markdown' ? markdownContent : JSON.stringify(response, null, 2);
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-in fade-in duration-150">
      <div className="bg-[#151619] border border-[#2a2c31] rounded w-full max-w-3xl max-h-[85vh] shadow-2xl flex flex-col overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-3.5 border-b border-[#2a2c31] bg-[#0c0d0e]">
          <div className="flex items-center space-x-3">
            <div className="h-7 w-7 rounded bg-[#4ade80]/10 border border-[#4ade80]/30 flex items-center justify-center text-[#4ade80]">
              <FileText className="h-4 w-4" />
            </div>
            <div>
              <h2 className="text-xs font-bold uppercase tracking-wider text-[#e1e1e1]">Forensic Remote Sensing Report</h2>
              <p className="text-[10px] text-[#8e9299] mono">QUERY_ID: {response.queryId}</p>
            </div>
          </div>

          <div className="flex items-center space-x-2 mono">
            <div className="flex items-center bg-[#151619] p-1 rounded border border-[#2a2c31] text-[10px]">
              <button
                onClick={() => setFormat('markdown')}
                className={`px-2.5 py-0.5 rounded transition-all uppercase font-bold ${
                  format === 'markdown' ? 'bg-[#2a2c31] text-[#4ade80]' : 'text-[#8e9299] hover:text-[#e1e1e1]'
                }`}
              >
                Markdown
              </button>
              <button
                onClick={() => setFormat('json')}
                className={`px-2.5 py-0.5 rounded transition-all uppercase font-bold ${
                  format === 'json' ? 'bg-[#2a2c31] text-[#4ade80]' : 'text-[#8e9299] hover:text-[#e1e1e1]'
                }`}
              >
                JSON Schema
              </button>
            </div>
            <button
              onClick={handleCopy}
              className="p-1.5 rounded border border-[#2a2c31] bg-[#151619] text-[#8e9299] hover:text-[#e1e1e1]"
              title="Copy"
            >
              {copied ? <Check className="h-3.5 w-3.5 text-[#4ade80]" /> : <Copy className="h-3.5 w-3.5" />}
            </button>
            <button
              onClick={handleDownload}
              className="flex items-center space-x-1 px-3 py-1.5 bg-[#4ade80] hover:brightness-110 text-black rounded text-[10px] font-bold uppercase tracking-wider transition-all"
            >
              <Download className="h-3 w-3" />
              <span>Download</span>
            </button>
            <button
              onClick={onClose}
              className="p-1.5 rounded border border-[#2a2c31] bg-[#151619] text-[#8e9299] hover:text-[#e1e1e1]"
            >
              <X className="h-3.5 w-3.5" />
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-5">
          <pre className="bg-[#0c0d0e] p-4 rounded border border-[#2a2c31] text-xs mono text-[#e1e1e1] whitespace-pre-wrap leading-relaxed overflow-x-auto shadow-inner">
            {format === 'markdown' ? markdownContent : JSON.stringify(response, null, 2)}
          </pre>
        </div>

        {/* Footer */}
        <div className="px-5 py-3 border-t border-[#2a2c31] bg-[#0c0d0e] flex items-center justify-between text-xs mono text-[#8e9299]">
          <div className="flex items-center space-x-1.5">
            <ShieldCheck className="h-3.5 w-3.5 text-[#4ade80]" />
            <span className="text-[10px]">Digital signature verified. Compatible with GIS reporting pipelines.</span>
          </div>
          <button
            onClick={onClose}
            className="px-3 py-1 bg-[#2a2c31] hover:bg-[#3d4047] text-[#e1e1e1] rounded font-bold uppercase text-[10px] transition-colors"
          >
            Done
          </button>
        </div>
      </div>
    </div>
  );
};
